
services:
  # Backend Python (FastAPI)
  backend:
    build:
      context: ./src/main/python
      dockerfile: ../docker/backend/Dockerfile
    container_name: exampleProject-backend
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    volumes:
      - ./src/main/python:/app
    environment:
      - PYTHONPATH=/app
    working_dir: /app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - exampleProject-network

  # Frontend Nuxt.js
  frontend:
    build:
      context: ./src/main/nuxt
      dockerfile: ../docker/nuxt/Dockerfile
      args:
        - BACKEND_API_URL=${BACKEND_API_URL}
    container_name: exampleProject-frontend
    restart: unless-stopped
    ports:
      - "${NUXT_PORT:-3000}:3000"
    environment:
      - NUXT_HOST=${NUXT_HOST:-0.0.0.0}
      - NUXT_PORT=${NUXT_PORT:-3000}
      - BACKEND_API_URL=${BACKEND_API_URL}
    networks:
      - exampleProject-network

  # Nginx Reverse Proxy
  nginx:
    build:
      context: ./src/main/docker/nginx
    container_name: exampleProject-nginx
    restart: unless-stopped
    ports:
      - "${NGINX_PORT:-80}:80"
    depends_on:
      - backend
      - frontend
    networks:
      - exampleProject-network

networks:
  exampleProject-network:
    driver: bridge

volumes:
  node_modules: